In [26]:
import numpy as np
from itertools import product

In [4]:
c = 1 # testing

In [2]:
n,k,p,m = 3,4,3,16

In [7]:
Cn_1 = c*n-1
total_digits = Cn_1 +1

In [31]:
bank_accounts = range(1,k+1)

In [40]:
vals = [np.array(i) for i in product(bank_accounts, repeat=total_digits)]

In [41]:
vals

[array([1, 1, 1]),
 array([1, 1, 2]),
 array([1, 1, 3]),
 array([1, 1, 4]),
 array([1, 2, 1]),
 array([1, 2, 2]),
 array([1, 2, 3]),
 array([1, 2, 4]),
 array([1, 3, 1]),
 array([1, 3, 2]),
 array([1, 3, 3]),
 array([1, 3, 4]),
 array([1, 4, 1]),
 array([1, 4, 2]),
 array([1, 4, 3]),
 array([1, 4, 4]),
 array([2, 1, 1]),
 array([2, 1, 2]),
 array([2, 1, 3]),
 array([2, 1, 4]),
 array([2, 2, 1]),
 array([2, 2, 2]),
 array([2, 2, 3]),
 array([2, 2, 4]),
 array([2, 3, 1]),
 array([2, 3, 2]),
 array([2, 3, 3]),
 array([2, 3, 4]),
 array([2, 4, 1]),
 array([2, 4, 2]),
 array([2, 4, 3]),
 array([2, 4, 4]),
 array([3, 1, 1]),
 array([3, 1, 2]),
 array([3, 1, 3]),
 array([3, 1, 4]),
 array([3, 2, 1]),
 array([3, 2, 2]),
 array([3, 2, 3]),
 array([3, 2, 4]),
 array([3, 3, 1]),
 array([3, 3, 2]),
 array([3, 3, 3]),
 array([3, 3, 4]),
 array([3, 4, 1]),
 array([3, 4, 2]),
 array([3, 4, 3]),
 array([3, 4, 4]),
 array([4, 1, 1]),
 array([4, 1, 2]),
 array([4, 1, 3]),
 array([4, 1, 4]),
 array([4, 2

In [38]:

const_array = np.array([ p**(n-1-i) for i in range(0,n) ])

In [39]:
const_array

array([9, 3, 1])

In [56]:
sums = vals * const_array

In [57]:
sums_ = np.sum(sums,axis=1)

In [58]:
sums_

array([13, 14, 15, 16, 16, 17, 18, 19, 19, 20, 21, 22, 22, 23, 24, 25, 22,
       23, 24, 25, 25, 26, 27, 28, 28, 29, 30, 31, 31, 32, 33, 34, 31, 32,
       33, 34, 34, 35, 36, 37, 37, 38, 39, 40, 40, 41, 42, 43, 40, 41, 42,
       43, 43, 44, 45, 46, 46, 47, 48, 49, 49, 50, 51, 52])

In [59]:
sums_ % m

array([13, 14, 15,  0,  0,  1,  2,  3,  3,  4,  5,  6,  6,  7,  8,  9,  6,
        7,  8,  9,  9, 10, 11, 12, 12, 13, 14, 15, 15,  0,  1,  2, 15,  0,
        1,  2,  2,  3,  4,  5,  5,  6,  7,  8,  8,  9, 10, 11,  8,  9, 10,
       11, 11, 12, 13, 14, 14, 15,  0,  1,  1,  2,  3,  4], dtype=int32)

In [60]:
new_index_sets = [np.argwhere(i[0]== sums_) for i in np.array(np.unique(sums_, return_counts=True)).T if i[1]>=2]

In [61]:
new_index_sets[0]

array([[3],
       [4]], dtype=int64)

In [68]:
for elem in sums[new_index_sets[0]][:2]:
    print(' '.join([str(i) for i in list(elem[0])]))

9 3 4
9 6 1


In [13]:
np.array([1,2,3]) * np.array([4,5,6])

array([ 4, 10, 18])

In [ ]:
#numpy not supported

In [89]:
c = 1 # testing
n,k,p,m = 3,4,3,16
Cn_1 = c*n-1
total_digits = Cn_1 +1
bank_accounts = range(1,k+1)
vals = [i for i in product(bank_accounts, repeat=total_digits)]

const_array = [ p**(n-1-i) for i in range(0,n) ]
#sums = [([a*b for a,b in zip(val, const_array)]) for val in vals ]
sums_ = [sum([a*b for a,b in zip(val, const_array)])%m for val in vals ]
#new_index_sets = [np.argwhere(i[0]== sums_) for i in np.array(np.unique(sums_, return_counts=True)).T if i[1]>=2]


In [96]:
from collections import defaultdict
# https://stackoverflow.com/questions/5419204/index-of-duplicates-items-in-a-python-list
def list_duplicates(seq):
    tally = defaultdict(list)
    for i,item in enumerate(seq):
        tally[item].append(i)
    return ((key,locs) for key,locs in tally.items() 
                            if len(locs)>1)

# for dup in sorted(list_duplicates(sums_)):
#     print(dup)
dups = [_ for _ in list_duplicates(sums_)]

In [99]:
dups[0][1]

[0, 25, 54]

In [105]:
for elem in  [vals[i] for i in dups[0][1]][:2]:
    print(' '.join([str(i) for i in elem]))

1 1 1
2 3 2
